blogapp/urls.py
from django.contrib import admin
from django.urls import path
from blogapp import views

app_name = 'blog'

urlpatterns = [
 # blog
    # path('',views.home, name='home'),
    path('category/',views.category, name='category'),
    path('article_list/<int:category_pk>', views.article_list, name='article_list'),
    path('writer/',views.writer, name='writer'),
    path('article_detail/<int:article_pk>', views.article_detail, name='article_detail'),
    path('article_writer/<int:category_pk>', views.article_writer, name='article_writer'),
    path('article/edit/<int:article_pk>', views.article_edit,name='article_edit'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from userapp import views

urlpatterns = [
    path('',views.home, name='home'),
    path('admin/', admin.site.urls),
    path('user/',include('userapp.urls')),
    path('blog/',include('blogapp.urls')),
    path('follow/',include('followapp.urls')),  
    path('tag/',include('tagapp.urls')),
]

tagapp/urls.py
from django.contrib import admin
from django.urls import path
from tagapp import views

app_name = 'tag'

urlpatterns = [
    
    # tag
    path('tag/<int:article_pk>', views.tag, name='tag'),

]

userapp/urls.py
from django.contrib import admin
from django.urls import path
from userapp import views

app_name = 'user'

urlpatterns = [
    # user
    path('',views.home, name='home'),
    path('register/',views.register, name='register'),
    path('login/',views.login, name='login'),
    path('logout/',views.logout, name='logout'),
    path('my_page/<int:user_pk>',views.my_page, name='my_page'),
]

crudapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from behaviors import Timestampable
import time
# Create your models here.

class Profile(models.Model):
  user = models.OneToOneField(User, on_delete=CASCADE, related_name='profile')
  nickname = models.CharField(max_length=64)
  intro = models.TextField()

  def __str__(self):
    return self.user.username


class Follow(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='follow')
  followers = models.ManyToManyField(User, blank=True, related_name='following')


class Category(models.Model):
  name = models.CharField(max_length=32)

  def __str__(self):
    return self.name

class Article(Timestampable):
  category = models.ForeignKey(Category, on_delete=models.CASCADE,blank=True, related_name='article')
  writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='article')
  title = models.CharField(max_length=64)
  content = models.TextField()
  is_deleted = models.BooleanField(default=False)
  

class Tag(Timestampable):
  name = models.CharField(max_length=64, unique=True)
  articles = models.ManyToManyField(Article, blank=True, related_name='tag')

crudapp/views.py
# from crudapp.models import Follow, Profile,Category,Article,Tag
# from django.shortcuts import get_object_or_404, redirect, render
# from django.contrib.auth.models import User
# from django.contrib import auth
# from django.contrib.auth import authenticate
# # Create your views here.

# def home(request):
#   users = User.objects.all()
#   context = {
#     'users':users
#   }
#   return render(request,'home.html',context)

# def register(request):
#   context = {
#     'error':
#     {
#       'state':False,
#       'msg':''
#     }
#   }
#   if request.method == 'POST':
#     userid = request.POST['id']
#     password = request.POST['password']
#     password_chk = request.POST['password_chk']
#     nickname = request.POST['nickname']
#     intro = request.POST['intro']
#     user = User.objects.filter(username = userid)
#     profile = Profile.objects.filter(nickname = nickname)
#     if not userid or not password_chk or not password or not nickname or not intro:
#       context['error']['state'] = True
#       context['error']['msg'] = '내용을 입력해주세요'      
#     if len(user) > 0:
#       context['error']['state'] = True
#       context['error']['msg'] = '아이디가 이미 존재합니다'
#     if password != password_chk:
#       context['error']['state'] = True
#       context['error']['msg'] = '비밀번호가 틀립니다'     
#     if len(profile) > 0:
#       context['error']['state'] = True
#       context['error']['msg'] = '이미 존재하는 닉네임입니다'
    
#     if not context['error']['state']:
#       user = User.objects.create_user(
#         username = userid,
#         password = password
#       )
#       Profile.objects.create(
#         user = user,
#         nickname = nickname,
#         intro = intro
#       )

#       Follow.objects.create(
#         user = user
#       )
#       auth.login(request, user)
#       return redirect('home')

#   return render(request,'register.html',context)


# def login(request):
#   context = {
#   'error':
#   {
#     'state':False,
#     'msg':''
#   }
# }
#   if request.method == 'POST':
#     userid = request.POST['id']
#     pwd = request.POST['password']

#     user = authenticate(username = userid, password = pwd)
#     if user is  None:
#       context['error']['state'] = True
#       context['error']['msg'] = '아이디와 비밀번호를 확인해주세요'

#     auth.login(request, user)
#     return redirect('home')

#   return render(request, 'login.html',context)


# def logout(request):
#   auth.logout(request)
#   return redirect('home')


# def my_page(request,user_pk):
#   is_followed = False
#   owner = User.objects.filter(pk = user_pk).first()
#   follow = Follow.objects.filter(user__pk = user_pk).first()
#   if request.user in follow.followers.all():
#     is_followed = True
#   context = {
#     'owner':owner,
#     'is_followed':is_followed,
#     'followers':follow.followers.all()
#   }
#   return render(request,'my_page.html',context)


# def follow(request, user_pk):
#   follow = Follow.objects.filter(user__pk = user_pk).first()
#   followers_list = follow.followers.all()
#   if request.user in followers_list:
#     follow.followers.remove(request.user)
#     return redirect('my_page',user_pk)
#   follow.followers.add(request.user)    
#   return redirect('my_page',user_pk)


# def category(request):
#   category = Category.objects.all()
#   context = {
#     'categories':category
#   }
#   return render(request, 'category.html',context)


# def article_list(request, category_pk):
#   article = Article.objects.filter(category__pk = category_pk).all()
#   category_pk = Category.objects.filter(pk = category_pk).first().pk
#   # Article category__pk.pk로 하면 Article이 없는 카테고리를 들어갈때 에러 발생함
#   context = {
#     'articles':article,
#     'category_pk':category_pk
#   }
#   return render(request, 'article_list.html',context)


# def writer(request):
#   category = Category.objects.all()
#   context = {
#    'categories':category
#    }
#   if request.method == 'POST':
#     title = request.POST['title']
#     content = request.POST['content']
#     category_pk = request.POST['category_pk']

#     if title and content and category_pk:
#       category = Category.objects.filter(pk = category_pk).first()    
#       Article.objects.create(
#         title = title,
#         writer = request.user,
#         content = content,
#         category=category
#       )
#       return redirect('category')
#   return render(request, 'writer.html',context)


# def article_detail(request, article_pk):
#   article = get_object_or_404(Article, pk = article_pk)
#   tag = Tag.objects.filter(articles__pk = article_pk).all()

#   context = {
#     'article':article,
#     'tags':tag
#   }
#   return render(request, 'article_detail.html',context)


# def article_writer(request, category_pk):
#   category = Category.objects.filter(pk = category_pk).first()
#   if request.method == 'POST':
#     title = request.POST['title']
#     content = request.POST['content']
#     Article.objects.create(
#       title = title,
#       content = content,
#       category = category,
#       writer = request.user
#     )
#     return redirect('article_list',category_pk)
#   context = {
#     'category':category
#   }
#   return render(request, 'article_writer.html',context)


# def tag(request, article_pk):
#   name = request.POST['tag']
#   article = Article.objects.filter(pk = article_pk).first()
#   tag = Tag.objects.filter(name = name).first()

#   if tag:
#     tag.articles.add(article)
#     return redirect('article_detail',article_pk)
  
#   new_tag = Tag.objects.create(
#     name = name
#   )
#   new_tag.articles.add(article)

#   return redirect('article_detail',article_pk)

crudapp/templates/article_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>글 세부 페이지</h1>
<hr>
<h3>제목</h3>
{{article.title}}
<hr>
<h3>작성자</h3>
{{article.writer}}
<hr>
<h3>내용</h3>
{{article.content}}
<hr>
<h3>해시태그</h3>
<form action="{% url 'tag:tag' article.pk %}" method="POST">
{% csrf_token %}
  <input type="text" name="tag" placeholder="태그입력">
  <button type="submit">등록하기</button>
</form>
{% for tag in tags %}

<span><strong>#{{tag.name}}</strong></span>
{% endfor %}
<hr>
<a href="{% url 'blog:article_list' article.category.pk %}">뒤로가기</a><br>

{% if article.writer == request.user %}
<a href="">수정하기</a>
<a href="">삭제하기</a>
{% endif %}

{% endblock content %}

crudapp/templates/my_page.html
{% extends 'base.html' %}

{% block content %}

<h1>{{owner.profile.nickname}}님 프로필</h1>
<hr>
{% if request.user.pk == owner.pk %}
<h4>아이디</h4>
{{owner}}
<br>
<hr>
<h4>자기소개</h4>
{{owner.profile.intro}}
<br>
<hr>
{% else %}
방문자 {{request.user}}님 환영합니다 <br>
<br>
<form action="{% url 'follow' owner.pk %}" method='POST'>
  {% csrf_token %}
  {% if is_followed %}
  <button type="submit">unfollow</button>
  {% else %}
  <button type="submit">follow</button>
  {% endif %}
</form>
{% endif %}
<h4>팔로워 보기</h4>
<select name="followers" id="follow-select">
  <option value="" selected>팔로워 보기</option>
  {% for follower in followers %}
  <option value="{{follower.pk}}">{{follower}}</option>
  {% endfor %}
</select>
<hr>
<a href="{% url 'user:home' %}">뒤로가기</a>
{% endblock content %}

crudapp/templates/register.html
{% extends 'base.html' %}

{% block content %}
<h1>회원가입페이지</h1>
{% if error.state %}
{{error.msg}}
{% endif %}
<form action="{% url 'register' %}"method='POST'>
  {% csrf_token %}
  <input type="text" name="id"placeholder='아이디입력'><br><br>
  <input type="password" name="password"placeholder='비번입력'><br><br>
  <input type="password_chk" name="password_chk"placeholder='비번확인'><br><br>
  <h2>프로필 설정</h2>
  <input type="text" name="nickname"placeholder='닉네임 입력'><br><br>
  <textarea name="intro"placeholder='자기소개 입력'></textarea><br><br>
  <button type="submit">회원가입하기</button>

</form><br>
<a href="{% url 'user:home' %}">뒤로가기</a>
{% endblock content %}