blogapp/urls.py
from django.contrib import admin
from django.urls import path
from blogapp import views

app_name = 'blog'

urlpatterns = [
 # blog
    # path('',views.home, name='home'),
    path('category/',views.category, name='category'),
    path('article_list/<int:category_pk>', views.article_list, name='article_list'),
    path('writer/',views.writer, name='writer'),
    path('article_detail/<int:article_pk>', views.article_detail, name='article_detail'),
    path('article_writer/<int:category_pk>', views.article_writer, name='article_writer'),
    path('article/edit/<int:article_pk>', views.article_edit,name='article_edit'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from userapp import views

urlpatterns = [
    path('',views.home, name='home'),
    path('admin/', admin.site.urls),
    path('user/',include('userapp.urls')),
    path('blog/',include('blogapp.urls')),
    path('follow/',include('followapp.urls')),  
    path('tag/',include('tagapp.urls')),
]

tagapp/urls.py
from django.contrib import admin
from django.urls import path
from tagapp import views

app_name = 'tag'

urlpatterns = [
    
    # tag
    path('tag/<int:article_pk>', views.tag, name='tag'),

]

userapp/urls.py
from django.contrib import admin
from django.urls import path
from userapp import views

app_name = 'user'

urlpatterns = [
    # user
    path('',views.home, name='home'),
    path('register/',views.register, name='register'),
    path('login/',views.login, name='login'),
    path('logout/',views.logout, name='logout'),
    path('my_page/<int:user_pk>',views.my_page, name='my_page'),
]

blogapp/models.py
from django.db import models

# Create your models here.

blogapp/views.py
from crudapp.models import Category,Article,Tag
from django.shortcuts import get_object_or_404, redirect, render


def category(request):
  category = Category.objects.all()
  context = {
    'categories':category
  }
  return render(request, 'category.html',context)


def article_list(request, category_pk):
  article = Article.objects.filter(category__pk = category_pk).all()
  category_pk = Category.objects.filter(pk = category_pk).first().pk
  # Article category__pk.pk로 하면 Article이 없는 카테고리를 들어갈때 에러 발생함
  context = {
    'articles':article,
    'category_pk':category_pk
  }
  return render(request, 'article_list.html',context)


def writer(request):
  category = Category.objects.all()
  context = {
   'categories':category
   }
  if request.method == 'POST':
    title = request.POST['title']
    content = request.POST['content']
    category_pk = request.POST['category_pk']

    if title and content and category_pk:
      category = Category.objects.filter(pk = category_pk).first()    
      Article.objects.create(
        title = title,
        writer = request.user,
        content = content,
        category=category
      )
      return redirect('blog:category')
  return render(request, 'writer.html',context)


def article_detail(request, article_pk):
  article = get_object_or_404(Article, pk = article_pk)
  tag = Tag.objects.filter(articles__pk = article_pk).all()

  context = {
    'article':article,
    'tags':tag
  }
  return render(request, 'article_detail.html',context)


def article_writer(request, category_pk):
  category = Category.objects.filter(pk = category_pk).first()
  if request.method == 'POST':
    title = request.POST['title']
    content = request.POST['content']
    Article.objects.create(
      title = title,
      content = content,
      category = category,
      writer = request.user
    )
    return redirect('blog:article_list',category_pk)
  context = {
    'category':category
  }
  return render(request, 'article_writer.html',context)


def article_edit(request, article_pk):
  article = get_object_or_404(Article,pk = article_pk)
  context = {
    'article':article,
    'state':False
  }
  if request.method == 'POST':
    title = request.POST['title']
    content = request.POST['content']
    if title and content:
      Article.objects.filter(pk=article_pk).update(
        title = title,
        content = content
      )
      return redirect('blog:article_detail',article_pk)
    context['state'] = True
  return render(request, 'article_edit.html',context)

blogapp/templates/article_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>글 세부 페이지</h1>
<hr>
<h3>제목</h3>
{{article.title}}
<hr>
<h3>작성자</h3>
{{article.writer}}
<hr>
<h3>내용</h3>
{{article.content}}
<hr>
<h3>해시태그</h3>
<form action="{% url 'tag:tag' article.pk %}" method="POST">
{% csrf_token %}
  <input type="text" name="tag" placeholder="태그입력">
  <button type="submit">등록하기</button>
</form>
{% for tag in tags %}

<span><strong>#{{tag.name}}</strong></span>
{% endfor %}
<hr>
<a href="{% url 'blog:article_list' article.category.pk %}">뒤로가기</a><br>

{% if article.writer == request.user %}
<a href="{% url 'blog:article_edit' article.pk %}">수정하기</a>
<a href="">삭제하기</a>
{% endif %}

{% endblock content %}

blogapp/templates/article_edit.html
{% extends 'base.html' %}

{% block content %}
<h1>글 수정하기</h1>
{% if state %}
<h4>내용을 전부 작성해주세요 !</h4>
{% endif %}

<form action="{% url 'blog:article_edit' article.pk %}"method="POST">
  {% csrf_token %}
  <select name="category_pk">
    <option selected>{{article.category.name}}</option>
  </select><br><br>
  <input type="text"name="title"value={{article.title}}><br><br>
  <textarea name="content">{{article.content}}</textarea><br><br>
<button type="submit">수정하기</button><br><br>
</form>


<a href="{% url 'blog:article_detail' article.pk %}">뒤로가기</a>


{% endblock content %}

blogapp/templates/article_list.html
{% extends 'base.html' %}

{% block content %}
<h1>글 목록</h1>

<br>
<ul>
  {% for article in articles %}
  <li>
    <a href="{% url 'blog:article_detail' article.pk %}">{{article.title}}</a>
    <small> [작성자 - {{article.writer}}]</small>
  </li>
  {% endfor %}
</ul>

<hr>
<a href="{% url 'blog:article_writer' category_pk %}">글작성하기</a>
<hr>

<a href="{% url 'blog:category' %}">뒤로가기</a>

{% endblock content %}

blogapp/templates/article_writer.html
{% extends 'base.html' %}

{% block content %}
<h1>글쓰기</h1>
<br>

<form action="{% url 'blog:article_writer' category.pk %}"method="POST">
  {% csrf_token %}
  <select name="category_pk">
    <option selected>{{category.name}}</option>
  </select><br><br>
  <input type="text"name="title"placeholder="제목입력"><br><br>
  <textarea name="content"placeholder='내용입력'></textarea><br><br>
<button type="submit">작성하기</button><br><br>
</form>


<a href="{% url 'blog:category' %}">뒤로가기</a>

{% endblock content %}

blogapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% block content %}
  {% endblock content %}
</body>
</html>

blogapp/templates/category.html
{% extends 'base.html' %}

{% block content %}
<h1>카테고리</h1>
<br>
<hr>
<ul>
{% for category in categories %}
<li><a href="{% url 'blog:article_list' category.pk %}">{{category}}</a></li>
{% endfor %}
</ul>
<hr>
<br>
<a href="{% url 'blog:writer' %}">글작성하기</a>
<hr>
<a href="{% url 'user:home' %}">뒤로가기</a>
{% endblock content %}

blogapp/templates/writer.html
{% extends 'base.html' %}

{% block content %}
<h1>글쓰기</h1>

<form action="{% url 'blog:writer' %}"method="POST">
  {% csrf_token %}
  <select name="category_pk">
    {% for category in categories %}
    <option value="{{category.pk}}">{{category}}</option>
    {% endfor %}
  </select><br><br>
  <input type="text"name="title"placeholder="제목입력"><br><br>
  <textarea name="content"placeholder='내용입력'></textarea><br><br>
<button type="submit">작성하기</button><br><br>
</form>




<a href="{% url 'blog:category' %}">뒤로가기</a>
{% endblock content %}