blogapp/urls.py
from django.contrib import admin
from django.urls import path
from blogapp import views

app_name = 'blog'

urlpatterns = [
 # blog
    # path('',views.home, name='home'),
    path('category/',views.category, name='category'),
    path('article_list/<int:category_pk>', views.article_list, name='article_list'),
    path('writer/',views.writer, name='writer'),
    path('article_detail/<int:article_pk>', views.article_detail, name='article_detail'),
    path('article_writer/<int:category_pk>', views.article_writer, name='article_writer'),
    path('article/edit/<int:article_pk>', views.article_edit,name='article_edit'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from userapp import views

urlpatterns = [
    path('',views.home, name='home'),
    path('admin/', admin.site.urls),
    path('user/',include('userapp.urls')),
    path('blog/',include('blogapp.urls')),
    path('follow/',include('followapp.urls')),  
    path('tag/',include('tagapp.urls')),
]

followapp/urls.py
    
from django.contrib import admin
from django.urls import path
from followapp import views

app_name = 'follow'

urlpatterns = [
  
  # follow
    path('follow/<int:user_pk>', views.follow, name='follow'),
]

userapp/urls.py
from django.contrib import admin
from django.urls import path
from userapp import views

app_name = 'user'

urlpatterns = [
    # user
    path('',views.home, name='home'),
    path('register/',views.register, name='register'),
    path('login/',views.login, name='login'),
    path('logout/',views.logout, name='logout'),
    path('my_page/<int:user_pk>',views.my_page, name='my_page'),
]

userapp/models.py
from django.db import models

# Create your models here.

userapp/views.py
from crudapp.models import Follow, Profile
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth import authenticate



def home(request):
  users = User.objects.all()
  context = {
    'users':users
  }
  return render(request,'home.html',context)

def register(request):
  context = {
    'error':
    {
      'state':False,
      'msg':''
    }
  }
  if request.method == 'POST':
    userid = request.POST['id']
    password = request.POST['password']
    password_chk = request.POST['password_chk']
    nickname = request.POST['nickname']
    intro = request.POST['intro']
    user = User.objects.filter(username = userid)
    profile = Profile.objects.filter(nickname = nickname)
    if not userid or not password_chk or not password or not nickname or not intro:
      context['error']['state'] = True
      context['error']['msg'] = '내용을 입력해주세요'      
    if len(user) > 0:
      context['error']['state'] = True
      context['error']['msg'] = '아이디가 이미 존재합니다'
    if password != password_chk:
      context['error']['state'] = True
      context['error']['msg'] = '비밀번호가 틀립니다'     
    if len(profile) > 0:
      context['error']['state'] = True
      context['error']['msg'] = '이미 존재하는 닉네임입니다'
    
    if not context['error']['state']:
      user = User.objects.create_user(
        username = userid,
        password = password
      )
      Profile.objects.create(
        user = user,
        nickname = nickname,
        intro = intro
      )

      Follow.objects.create(
        user = user
      )
      auth.login(request, user)
      return redirect('user:home')

  return render(request,'register.html',context)


def login(request):
  context = {
  'error':
  {
    'state':False,
    'msg':''
  }
}
  if request.method == 'POST':
    userid = request.POST['id']
    pwd = request.POST['password']

    user = authenticate(username = userid, password = pwd)
    if user is  None:
      context['error']['state'] = True
      context['error']['msg'] = '아이디와 비밀번호를 확인해주세요'

    auth.login(request, user)
    return redirect('user:home')

  return render(request, 'login.html',context)


def logout(request):
  auth.logout(request)
  return redirect('user:home')


def my_page(request,user_pk):
  is_followed = False
  owner = User.objects.filter(pk = user_pk).first()
  follow = Follow.objects.filter(user__pk = user_pk).first()
  if request.user in follow.followers.all():
    is_followed = True
  context = {
    'owner':owner,
    'is_followed':is_followed,
    'followers':follow.followers.all()
  }
  return render(request,'my_page.html',context)

userapp/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>홈페이지</h1>

{% if user.is_authenticated %}
<ul>
  {% for user in users %}
  <li><a href="{% url 'user:my_page' user.pk %}">{{user}}</a></li>
  {% endfor %}
  </ul>
  <hr>
{{user.profile.nickname}}님 환영합니다 !
<br><br>
<a href="{% url 'user:my_page' user.pk %}">마이페이지 이동</a> 
<hr>
<h3>커뮤니티</h3>
<a href="{% url 'blog:category' %}">글쓰러가기</a>
<hr>
<br>
<a href="{% url 'user:logout' %}">로그아웃하기</a>
{% else %}
<a href="{% url 'user:login' %}">로그인하기</a><br>
<a href="{% url 'user:register' %}">회원가입하기</a>
{% endif %}
{% endblock content %}context

userapp/templates/login.html
{% extends 'base.html' %}

{% block content %}
<h1>로그인</h1>

{% if error.state %}
{{error.msg}}
{% endif %}
<form action="{% url 'user:login' %}" method='POST'>
  {% csrf_token %}
  <input type="text" name="id" placeholder='아이디입력'><br><br>
  <input type="password" name="password" placeholder='비번입력'><br><br>
  <button type="submit">로그인하기</button>
</form>
<a href="{% url 'user:home' %}">뒤로가기</a>

{% endblock content %}

userapp/templates/my_page.html
{% extends 'base.html' %}

{% block content %}

<h1>{{owner.profile.nickname}}님 프로필</h1>
<hr>
{% if request.user.pk == owner.pk %}
<h4>아이디</h4>
{{owner}}
<br>
<hr>
<h4>자기소개</h4>
{{owner.profile.intro}}
<br>
<hr>
{% else %}
방문자 {{request.user}}님 환영합니다 <br>
<br>
<form action="{% url 'follow:follow' owner.pk %}" method='POST'>
  {% csrf_token %}
  {% if is_followed %}
  <button type="submit">unfollow</button>
  {% else %}
  <button type="submit">follow</button>
  {% endif %}
</form>
{% endif %}
<h4>팔로워 보기</h4>
<select name="followers" id="follow-select">
  <option value="" selected>팔로워 보기</option>
  {% for follower in followers %}
  <option value="{{follower.pk}}">{{follower}}</option>
  {% endfor %}
</select>
<hr>
<a href="{% url 'user:home' %}">뒤로가기</a>
{% endblock content %}

userapp/templates/register.html
{% extends 'base.html' %}

{% block content %}
<h1>회원가입페이지</h1>
{% if error.state %}
{{error.msg}}
{% endif %}
<form action="{% url 'user:register' %}"method='POST'>
  {% csrf_token %}
  <input type="text" name="id"placeholder='아이디입력'><br><br>
  <input type="password" name="password"placeholder='비번입력'><br><br>
  <input type="password_chk" name="password_chk"placeholder='비번확인'><br><br>
  <h2>프로필 설정</h2>
  <input type="text" name="nickname"placeholder='닉네임 입력'><br><br>
  <textarea name="intro"placeholder='자기소개 입력'></textarea><br><br>
  <button type="submit">회원가입하기</button>

</form><br>
<a href="{% url 'user:home' %}">뒤로가기</a>
{% endblock content %}